

INSERT INTO ACCOUNT
(NAME, INSTANCE_ID, ACCOUNT_TYPE_ID, BANK_ID, CURRENCY_ID, INTERNAL, INITIAL_BALANCE)
VALUES ('INCOME', 'DEFAULT', 0, 0, 'INR', true, 0);

INSERT INTO ACCOUNT
(NAME, INSTANCE_ID, ACCOUNT_TYPE_ID, BANK_ID, CURRENCY_ID, INTERNAL, INITIAL_BALANCE)
VALUES ('EXPENSE', 'DEFAULT', 0, 0, 'INR', true, 0);


